<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20160308135059 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE kaystrobach_faq_domain_model_answer (persistence_object_identifier VARCHAR(40) NOT NULL, question VARCHAR(40) DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, answer LONGTEXT DEFAULT NULL, INDEX IDX_ACF2394AB6F7494E (question), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE kaystrobach_faq_domain_model_category (persistence_object_identifier VARCHAR(40) NOT NULL, title VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE kaystrobach_faq_domain_model_question (persistence_object_identifier VARCHAR(40) NOT NULL, creator VARCHAR(40) DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, question LONGTEXT DEFAULT NULL, category LONGTEXT DEFAULT NULL, roleidentifiers LONGTEXT DEFAULT NULL COMMENT '(DC2Type:simple_array)', INDEX IDX_9D9E688FBC06EA63 (creator), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE kaystrobach_faq_domain_model_answer ADD CONSTRAINT FK_ACF2394AB6F7494E FOREIGN KEY (question) REFERENCES kaystrobach_faq_domain_model_question (persistence_object_identifier)");
		$this->addSql("ALTER TABLE kaystrobach_faq_domain_model_question ADD CONSTRAINT FK_9D9E688FBC06EA63 FOREIGN KEY (creator) REFERENCES typo3_flow_security_account (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE kaystrobach_faq_domain_model_answer DROP FOREIGN KEY FK_ACF2394AB6F7494E");
		$this->addSql("DROP TABLE kaystrobach_faq_domain_model_answer");
		$this->addSql("DROP TABLE kaystrobach_faq_domain_model_category");
		$this->addSql("DROP TABLE kaystrobach_faq_domain_model_question");
	}
}