<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20160308160957 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE kaystrobach_faq_domain_model_answer ADD creator VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE kaystrobach_faq_domain_model_answer ADD CONSTRAINT FK_ACF2394ABC06EA63 FOREIGN KEY (creator) REFERENCES typo3_flow_security_account (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_ACF2394ABC06EA63 ON kaystrobach_faq_domain_model_answer (creator)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE kaystrobach_faq_domain_model_answer DROP FOREIGN KEY FK_ACF2394ABC06EA63");
		$this->addSql("DROP INDEX IDX_ACF2394ABC06EA63 ON kaystrobach_faq_domain_model_answer");
		$this->addSql("ALTER TABLE kaystrobach_faq_domain_model_answer DROP creator");
	}
}