<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20160308161622 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE kaystrobach_faq_domain_model_answer ADD creationdate DATETIME NOT NULL, ADD expirationdate DATETIME DEFAULT NULL");
		$this->addSql("ALTER TABLE kaystrobach_faq_domain_model_question ADD creationdate DATETIME NOT NULL, ADD expirationdate DATETIME DEFAULT NULL");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE kaystrobach_faq_domain_model_answer DROP creationdate, DROP expirationdate");
		$this->addSql("ALTER TABLE kaystrobach_faq_domain_model_question DROP creationdate, DROP expirationdate");
	}
}